name: AutoTrigger

on:
  workflow_dispatch:
  schedule:
    - cron: '30 */4 * * *'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Init Env
      run: |
        sudo -E apt-get -qq install git curl wget openssl -y  
        sudo echo "180.76.198.77 gitee.com" | sudo tee -a /etc/hosts
        sudo echo "182.255.33.134 gitee.com" | sudo tee -a /etc/hosts

    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Delete workflow runs
      uses: bigbugcc/delete-workflow-runs@main
      with:
        keep_minimum_runs: 2

    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 4
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}