name: WarpPlus

on:
  workflow_dispatch:

env:
  repo: ''
  force_active: true

jobs:
  auto_getting_traffic:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checking'
        uses: actions/checkout@v2

      - name: 'Setting Python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'

      - name: 'Getting WARP+ Traffic'
        env:
          DEVICEID: ${{ secrets.WARP_DEVICEID }}      
        run: python ./bin/app/warp.py